production: no
db_name: openitcockpit
db_user: oitc
db_user_password: mysql_password
db_root_password: root_password
mailserver: localhost
smtpport: 25
senderaddress: oitc@example.com
user_firstname: root
user_surname: wheel
user_email: root@example.com
user_password: Apd67z
phpnsta_user_name: phpnsta
phpnsta_user_password: phpnstasuperwassword
ssh_key_public_slave: ''
nagios_home: /var/lib/nagios
after_export_user: nagios
api_host: ''
api_user: ''
api_password: ''
api_user_ldap: '0'
