---
- include: naemon.yml

- name: enable production mode
  become: yes
  hostname:
    name: master
  when: oitc.production
  register: production_mode

- name: rsync files
  become: yes
  synchronize:
    src: ./../
    dest: "{{ nginx.doc_root }}"
    rsync_opts:
      - "--exclude=.git,.vagrant"

- name: Make my directory tree readable
  become: yes
  file:
    path: "{{ nginx.doc_root }}"
    owner: vagrant
    group: www-data
    mode: 0774
    recurse: yes

- name: Ensure that Cache folder ist present and writeable
  file:
    path: "{{ nginx.doc_root }}/app/tmp/"
    owner: www-data
    group: www-data
    mode: 0777
    recurse: yes

- name: set setup wrapper
  become: yes
  template:
    src: setup_wrapper.sh.j2
    dest: /usr/share/openitcockpit/setup_wrapper.sh
    owner: root
    group: root
    mode: 700

- name: start setup wrapper
  become: yes
  command: /usr/share/openitcockpit/setup_wrapper.sh
  when: (db_created.changed or production_mode.changed)